//! The item catalogue.
//!
//! Albion identifies items by a numeric id that shifts whenever the game
//! updates its data. The mapping to a stable unique name and a display name
//! comes from community-maintained dumps.
//!
//! A snapshot is embedded in the binary so the application works with no
//! network access at all. `loot-ledger --refresh-items` updates it from the
//! community dump, and the embedded copy is the fallback when that fails.

use std::collections::HashMap;
use std::sync::OnceLock;

/// The embedded snapshot, generated by `tools/extract-items.js`.
///
/// Columns: numeric id, unique name, display name — tab separated.
const EMBEDDED: &str = include_str!("assets/items.tsv");

/// Community-maintained dump of the item table.
const UPSTREAM_URL: &str =
    "https://raw.githubusercontent.com/ao-data/ao-bin-dumps/master/formatted/items.txt";

/// An item as loot-ledger knows it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Item {
    /// The game's numeric item id, as it appears on the wire.
    pub num_id: i64,
    /// Stable unique name, e.g. `T4_BAG_H`.
    pub unique_name: String,
    /// Human-readable name, e.g. `Adept's Bag`.
    pub display_name: String,
}

/// An item catalogue, indexed by numeric id.
#[derive(Debug)]
pub struct Catalogue {
    items: HashMap<i64, Item>,
    /// Where the data came from, for the status line in the UI.
    source: &'static str,
}

impl Catalogue {
    /// Load the embedded snapshot.
    fn embedded() -> Catalogue {
        let mut items = HashMap::with_capacity(12_000);

        for line in EMBEDDED.lines() {
            if line.is_empty() {
                continue;
            }
            let mut cols = line.splitn(3, '\t');
            let (Some(num_id), Some(unique), Some(display)) =
                (cols.next(), cols.next(), cols.next())
            else {
                continue;
            };
            let Ok(num_id) = num_id.parse::<i64>() else {
                continue;
            };
            items.insert(
                num_id,
                Item {
                    num_id,
                    unique_name: unique.to_owned(),
                    display_name: display.to_owned(),
                },
            );
        }

        Catalogue {
            items,
            source: "embedded snapshot",
        }
    }

    /// Look up an item by its numeric id.
    ///
    /// Unknown ids are common after a game update and must never be fatal, so
    /// this returns `None` and the caller renders the raw id.
    pub fn get(&self, num_id: i64) -> Option<&Item> {
        self.items.get(&num_id)
    }

    /// Number of items loaded, for the status line.
    pub fn len(&self) -> usize {
        self.items.len()
    }

    /// Always false; present so `len` does not trip the usual lint.
    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }

    /// Where this catalogue came from.
    pub fn source(&self) -> &'static str {
        self.source
    }
}

/// The process-wide catalogue, loaded once on first use.
pub fn catalogue() -> &'static Catalogue {
    static CATALOGUE: OnceLock<Catalogue> = OnceLock::new();
    CATALOGUE.get_or_init(Catalogue::embedded)
}

/// Fetch a fresh item table and write it to `path`.
///
/// Returns the number of rows written. Used by `loot-ledger --refresh-items`;
/// the caller decides whether to restart so the new data takes effect.
pub fn refresh_to_file(path: &std::path::Path) -> std::io::Result<usize> {
    let body = fetch(UPSTREAM_URL)?;

    let mut out = String::with_capacity(body.len());
    let mut rows = 0usize;

    for line in body.lines() {
        // Format: "<numId>: <UNIQUE_NAME> : <Display Name>"
        let Some(first) = line.find(':') else {
            continue;
        };
        let Ok(num_id) = line[..first].trim().parse::<i64>() else {
            continue;
        };
        let rest = &line[first + 1..];
        let (unique, display) = match rest.find(':') {
            Some(i) => (rest[..i].trim(), rest[i + 1..].trim()),
            None => (rest.trim(), rest.trim()),
        };
        if unique.is_empty() {
            continue;
        }
        out.push_str(&format!(
            "{num_id}\t{}\t{}\n",
            unique,
            if display.is_empty() { unique } else { display }
        ));
        rows += 1;
    }

    if rows == 0 {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "upstream item table was empty or unrecognised",
        ));
    }

    std::fs::write(path, out)?;
    Ok(rows)
}

fn fetch(url: &str) -> std::io::Result<String> {
    // std has no HTTP client, and loot-ledger takes no dependencies, so shelling
    // out to curl is the pragmatic choice for a maintenance command that runs
    // a handful of times, not on the capture path.
    let out = std::process::Command::new("curl")
        .args(["-fsSL", "--max-time", "30", url])
        .output()
        .map_err(std::io::Error::other)?;

    if !out.status.success() {
        return Err(std::io::Error::other(format!(
            "curl exited with {}",
            out.status
        )));
    }

    String::from_utf8(out.stdout)
        .map_err(|_| std::io::Error::new(std::io::ErrorKind::InvalidData, "response was not UTF-8"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_a_plausible_number_of_items() {
        let c = catalogue();
        assert!(c.len() > 10_000, "only {} items loaded", c.len());
        assert!(!c.is_empty());
    }

    #[test]
    fn resolves_a_known_item() {
        let c = catalogue();
        let item = c.get(2).expect("item 2 should exist");
        assert_eq!(item.unique_name, "T3_2H_TOOL_TRACKING");
        assert_eq!(item.display_name, "Journeyman's Tracking Toolkit");
    }

    #[test]
    fn unknown_ids_return_none_rather_than_panicking() {
        assert!(catalogue().get(i64::MAX).is_none());
        assert!(catalogue().get(-1).is_none());
        assert!(catalogue().get(0).is_none());
    }

    #[test]
    fn every_row_has_all_three_columns() {
        let mut rows = 0;
        for line in EMBEDDED.lines().filter(|l| !l.is_empty()) {
            assert_eq!(line.split('\t').count(), 3, "malformed row: {line}");
            rows += 1;
        }
        assert_eq!(rows, catalogue().len());
    }

    #[test]
    fn names_never_contain_a_tab_or_newline() {
        for item in catalogue().items.values() {
            assert!(!item.display_name.contains('\t'));
            assert!(!item.display_name.contains('\n'));
            assert!(!item.unique_name.contains('\t'));
        }
    }
}
